import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Fredoka } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["400", "600", "700"], // normal, semibold, bold
  subsets: ["latin"],
});

const poppinsBold = Poppins({
  variable: "--font-poppinsbold",
  weight: ["700"], // normal, semibold, bold
  subsets: ["latin"],
});

const fredoka = Fredoka({
  variable: "--font-fredoka",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} ${poppinsBold.variable} ${fredoka.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
